repos:
  # Adding custom cleaning utility
  - repo: local
    hooks:
      - id: clean-directory
        name: clean directory
        entry: >
          bash -c 'clean() {
            local directory="$1";
            if [ ! -d "$directory" ]; then
              echo "Directory '\''$directory'\'' not found";
              return;
            fi;
            find "$directory" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null;
            find "$directory" -type f -name ".DS_Store" -exec rm -f {} + 2>/dev/null;
            find "$directory" -type d -name "catboost_info" -exec rm -r {} + 2>/dev/null;
            find "$directory" -type d -name ".ruff_cache" -exec rm -r {} + 2>/dev/null;
            find "$directory" -type d -name ".ipynb_checkpoints" -exec rm -r {} + 2>/dev/null;
          }; clean .'
        language: system
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json|\.ipynb$
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json|\.ipynb$
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.5"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format
      - id: ruff
        name: ruff-notebooks
        args: [--fix]
        files: \.ipynb$
