"""02_Portfolio_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmILu375smzDYlIRzjsDlH8-qXGq652X

### Prepare Environment
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats
import seaborn as sns
import yfinance

# plt.style.use('seaborn')

START = "2023-01-01"
END = "2025-08-15"
# tickers = ['BTC-USD','EURUSD=X','^DJI','GC=F','IS3N.DE','VWCE.DE','ALPHA.AT','MSFT']
# tickers = ['AEGN.AT','ALPHA.AT','CAIROMEZ.AT','OTOEL.AT', 'VIO.AT']
tickers = ["VUAA.L", "VUSA.L", "VWO", "VWCE.DE", "VOO", "QQQ", "QDVE.DE", "IEMG", "IS3N.DE"]

"""### Download Data"""

raw = yfinance.download(tickers, start=START, end=END)

# data = raw['Adj Close']
data = raw["Close"]
returns = data.pct_change(fill_method=None).dropna()

"""### Equal Weight Portfolio"""

no_assets = returns.shape[1]
no_assets

weights = [1 / no_assets for _ in range(no_assets)]
# assert sum(weights) == 1
weights, sum(weights)

ewp_returns = returns.mul(weights, axis="columns").sum(axis=1)  # Equal Weight Portfolio Returs - Alternative - 1
ewp_returns = returns.dot(weights)  # Equal Weight Portfolio Returs - Alternative - 2

pret = returns.copy()
pret["EWP"] = ewp_returns
pret

summary = pret.describe().T[["mean", "std"]]  # .rename(columns={'mean':'Returns','std':'Risk'})
summary.columns = ["Return", "Risk"]
summary.Return = summary.Return * 252
summary.Risk = summary.Risk * np.sqrt(252)
summary

summary.plot(kind="scatter", x="Risk", y="Return", figsize=(16, 4), s=50, fontsize=15)
for i in summary.index:
    plt.annotate(i, xy=(summary.loc[i, "Risk"] + 0.00005, summary.loc[i, "Return"] + 0.00005), size=10)
plt.xlabel("Risk (std)", fontsize=15)
plt.ylabel("Mean Return", fontsize=15)
plt.title("Mean Variance Analysis", fontsize=15)
plt.show()

"""### Random Portfolios"""


def ann_returns(returns_df):
    summary = returns_df.agg(["mean", "std"]).T
    summary.columns = ["Return", "Risk"]
    summary.Return = summary.Return * 252
    summary.Risk = summary.Risk * np.sqrt(252)
    return summary


ret = data.pct_change().dropna()
noa = data.shape[1]
nop = 10_000
np.random.seed(1990)
matrix = np.random.random(noa * nop).reshape(nop, noa)
weights = matrix / matrix.sum(axis=1, keepdims=True)
assert weights.sum() == nop

port_ret = ret.dot(weights.T)

port_summary = ann_returns(port_ret)

plt.figure(figsize=(16, 4))
plt.scatter(port_summary.loc[:, "Risk"], port_summary.loc[:, "Return"], s=20, color="Red")
plt.scatter(summary.loc[:, "Risk"], summary.loc[:, "Return"], s=50, color="Black", marker="D")
for i in summary.index:
    plt.annotate(i, xy=(summary.loc[i, "Risk"] + 0.005, summary.loc[i, "Return"] + 0.005), size=10)
plt.xlabel("Risk (std)", fontsize=15)
plt.ylabel("Mean Return", fontsize=15)
plt.title("Risk vs Return", fontsize=15)
plt.show()
